#!/usr/bin/env ruby

# The script requires a security group as first positional parameter, a port number as second, a protocol as a third  ( UDP or TCP ) and an AWS service as fourth
# We don't doublecheck validity of either parameter, so use at your own peril!!!
# This script will make sure that the specified SG and TCP port/protocol accept incoming traffic from whichever AWS service we query the AWS endpoint for

# Stuff we need
require 'aws-sdk'
require 'json'
require 'open-uri'

# Setting the positional parameters
security_group = ARGV[0]
security_group_port = ARGV[1]
protocol = ARGV[2]
service = ARGV[3]
# Raise exception if any positional parameter is not set
raise 'pass positional parameters: sg_name sg_port udp/tcp AWS_service' unless security_group and security_group_port and protocol and service

# cfn_endpoint_ranges is a unidimensional array whose components are ipadresses with netmask ( x.x.x.x/y ) retrieved from AWS, those are the ranges that provide the CLOUDFRONT service
endpoint_ranges = JSON.parse(open("https://ip-ranges.amazonaws.com/ip-ranges.json") { |io| io.read })["prefixes"].select {|p| p["service"]=="CLOUDFRONT"}.map{|component| component['ip_prefix']};


# ==========ENDBEGIN===================
# Ex: Print each element of the array
endpoint_ranges.each do |component|
  puts "el component es"
  puts "#{component}"
end

#puts security_group
#puts security_group_port
# =========ENDEND=====================